### ISSUE TITLE
Bug: Mobile layout Sign in / Wallet links invisible

### ISSUE THREAD

**Issue by lion-200** [steem-engine-exchange/steem-engine-dex#120]
On mobile devices, the sign-in and/or waller links are not displayed

**Comment by lion-200** [comment]
<img width="375" alt="Bestand_001" src="https://user-images.githubusercontent.com/50720354/68785379-66c2c180-063e-11ea-8401-ece5946ca26d.png">

**Comment by Vheissu** [comment]
Fixed. Still might require some design loving, but the links are now working on mobile.
