### ISSUE TITLE
market UI components overlapping on 13" screen

### ISSUE THREAD

**Issue by harpagon210** [steem-engine-exchange/steem-engine-dex#122]
The market UI components are overlapping on my 13" screen (see screenshot below).

<img width="1280" alt="Screen Shot 2019-11-13 at 11 20 42 AM" src="https://user-images.githubusercontent.com/35413982/68788074-4e37b480-0608-11ea-981f-6c9dbbb9c535.png">

**Comment by Vheissu** [comment]
Thank you for reporting this @harpagon210

**Comment by Vheissu** [comment]
@horlorlahdeh You have been working quite a bit on the UI, would you please check this out for me? 13" is a fairly common size for users on MacBook's and definitely something we want to address. Thank you.

**Comment by horlorlahdeh** [comment]
I'll get to that and push it together with the next PR
