### ISSUE TITLE
Conversion History Page For Logged In Account Doesn't Work Properly

### ISSUE THREAD

**Issue by gadrian78** [steem-engine-exchange/steem-engine-dex#139]
**The listed conversion seems to be a test conversion by aggroed from March this year. Nothing about my conversions (i.e. deposits and withdrawals).**

![image](https://user-images.githubusercontent.com/31955497/68991662-b46f4200-0869-11ea-9f70-2eeab4087f69.png)

**Now that I look at it, it doesn't seem to work properly on the main front end either.**

![image](https://user-images.githubusercontent.com/31955497/68991682-fdbf9180-0869-11ea-8d50-51d381fc38ec.png)

**I've done both deposits and withdrawals to and from Steem-Engine.**

**Comment by Vheissu** [comment]
Thanks for reporting this @gadrian78 I have fixed this up and deploying now. Let me know if you spot anything funky on the site again. Much appreciated.
