### ISSUE TITLE
If "Hide Zero Balances" is On and you go to your wallet from another page, zero balances aren't hidden; Same for "Only Show Favorites"

### ISSUE THREAD

**Issue by gadrian78** [steem-engine-exchange/steem-engine-dex#141]
![image](https://user-images.githubusercontent.com/31955497/68992227-7a09a300-0871-11ea-9e01-d0a8c6d0d02c.png)

![image](https://user-images.githubusercontent.com/31955497/68992296-36fbff80-0872-11ea-9b2d-52e6512c8204.png)

**Comment by Vheissu** [comment]
@gadrian78 This has been fixed. Thanks for reporting.
