### ISSUE TITLE
Gray out Buy / Sell link, depending which on which button is active on the exchange page

### ISSUE THREAD

**Issue by gadrian78** [steem-engine-exchange/steem-engine-dex#142]
Currently both BUY and SELL links remain active when they should work as a switch, the way the new UI has been designed.

![image](https://user-images.githubusercontent.com/31955497/68992509-08cbef00-0875-11ea-8bc6-c770a2a9e74b.png)

I believe when the BUY button is active, the BUY link marked above should be grayed out, so that the user can see the only alternative is to click the SELL link. And vice-versa.

**Comment by Vheissu** [comment]
@gadrian78 Agreed. This has now been fixed. Thanks again.
