### ISSUE TITLE
Feature: Wallet estimated value

### ISSUE THREAD

**Issue by lion-200** [steem-engine-exchange/steem-engine-dex#148]
**Is your feature request related to a problem? Please describe.**
New DEX misses the Estimated Value displayed in old Dex Wallet page

**Describe the solution you'd like**
Add this information to new DEX

![image](https://user-images.githubusercontent.com/50720354/68994633-74b65380-0885-11ea-8e88-4e55de9aeea2.png)

**Comment by Vheissu** [comment]
Merged into `develop`
