### ISSUE TITLE
Bug: Exchange Depth chart sell orders displayed in wrong order

### ISSUE THREAD

**Issue by lion-200** [steem-engine-exchange/steem-engine-dex#150]
**Describe the bug**
In exchange page, the depth chart, sell orders are displayed in wrong order. They should be increasing from left to right, it is now the other way around.

**To Reproduce**
1. Go to Exchange page
2. Click on Depth icon
3. Check sell orders (red)

**Expected behavior**
Expected order is ascending from left to right.

**Screenshots**
![image](https://user-images.githubusercontent.com/50720354/68995888-20b26b80-0893-11ea-9c8a-2cb2d94db08f.png)

**Comment by Vheissu** [comment]
This is related to the issue we saw in the buy book. It's a simple Array.reverse on the data, I think.

**Comment by Vheissu** [comment]
https://github.com/steem-engine-exchange/steem-engine-dex/pull/172

@lion-200 Deployed to the test site. Please tell me what you think of the change moving the chart above the other boxes, I think it looks way better. https://qa.steem-engine.com
