### ISSUE TITLE
Bug: Buy/Sell orders request wrong key

### ISSUE THREAD

**Issue by rychardemanne** [steem-engine-exchange/steem-engine-dex#165]
I did make a few trade transactions yesterday and they worked fine, but today have come across this error.

It effectively means no txs can be done at all.

Tried to sell, then input steemconnect username and active key.
The next screen says that the *posting key* is required and takes you back to input page.
If you then use the posting key, as suggested, there is a tx error message about the missing authorisation.

So, in essence, it asks for the posting rather than the active key but then the tx fails because of the wrong key.

As I said, wasn't getting this yesterday but has appeared today.

Many thanks

**Comment by lion-200** [comment]
![image](https://user-images.githubusercontent.com/50720354/69179040-19959280-0b0b-11ea-88ce-11b956ff2700.png)

**Comment by lion-200** [comment]
Thanks for raising this issue. I was able to reproduce this issue, both on new DEX and current DEX. We are looking into it.

**Comment by Vheissu** [comment]
@rychardemanne Thanks for letting us know. This is definitely a bug, we'll get this sorted pronto.

**Comment by Vheissu** [comment]
@rychardemanne Thanks for reporting. This should now be fixed. A release is currently going out https://github.com/steem-engine-exchange/steem-engine-dex/pull/171

**Comment by rychardemanne** [comment]
> 
> 
> @rychardemanne Thanks for reporting. This should now be fixed. A release is currently going out #171

Thanks, glad i could help.
