### ISSUE TITLE
Feature: Missing ability to "issue" self owned tokens

### ISSUE THREAD

**Issue by Vheissu** [steem-engine-exchange/steem-engine-dex#183]
Token owners currently have no way to issue their created tokens.

**Comment by lion-200** [comment]
This is already implemented. Issue button is available on Token History. Maybe better to move it to somewhere more visible?

![image](https://user-images.githubusercontent.com/50720354/69366113-ea5f5c80-0c95-11ea-9198-0a568c7eda1f.png)

![image](https://user-images.githubusercontent.com/50720354/69366122-ee8b7a00-0c95-11ea-894d-a404db391bb7.png)
