### ISSUE TITLE
Sorting on Tokens page broken

### ISSUE THREAD

**Issue by gadrian78** [steem-engine-exchange/steem-engine-dex#207]
Sorting on the Tokens page is linked only to the pegged tokens. Example for sorting by the ticker, but the same effect can be reproduced on the name of the token, and probably all the other fields, but haven't continued further.
![image](https://user-images.githubusercontent.com/31955497/69873818-0c726380-12c2-11ea-86bb-e10aad3b4264.png)

**Comment by gadrian78** [comment]
Hi @lion-200!

It isn't fixed yet, but I notice a new bug has been introduced instead (maybe it was already present, but didn't see it before): rows are "doubled". See what I mean here:
![image](https://user-images.githubusercontent.com/31955497/70424825-b0090400-1a78-11ea-99bc-7ebc4dfc33bf.png)

**Comment by lion-200** [comment]
Hey mate @gadrian78 , thanks for the message. Some calls are changed on this page. Can you please check this again? Looks like the sorting is working now and double records are removed.

**Comment by gadrian78** [comment]
Yep, everything works perfectly about sorting @lion-200! Well, except one minor detail I've noticed now: the "Token Information" image link doesn't seem to do anything here on the Tokens page.

**Comment by gadrian78** [comment]
Hmm, I discovered today that sorting is partial or rather "in chunks" @lion-200 .

Here's what I mean. Both screenshots are taken from the same page, without any other action between them other than scrolling down a bit to take the second screenshot.
![image](https://user-images.githubusercontent.com/31955497/70916453-609c7800-2024-11ea-9c36-dfc4607d8833.png)
![image](https://user-images.githubusercontent.com/31955497/70916715-d0aafe00-2024-11ea-9a39-bc4604e69954.png)

**Comment by lion-200** [comment]
I see that sorting is removed from Wallet page for some reason. Putting this issue on hold until a correct implementation is applied.

**Comment by Vheissu** [comment]
I have fixed this now guys @lion-200
