### ISSUE TITLE
Feature request: Search for tokens

### ISSUE THREAD

**Issue by gadrian78** [steem-engine-exchange/steem-engine-dex#208]
Steem-engine V2 doesn't seem to have (or it's not active yet) a search for tokens option, which is present in V1 and very useful sometimes:
![image](https://user-images.githubusercontent.com/31955497/69874263-324c3800-12c3-11ea-8ac6-a7b39a6617c2.png)

Maybe that's a good place to add it?
![image](https://user-images.githubusercontent.com/31955497/69874412-9c64dd00-12c3-11ea-8700-37e56db618d5.png)

**Comment by lion-200** [comment]
Thanks for creating the issue @gadrian78 ! This is implemented and will be deployed with the upcoming release.
