### ISSUE TITLE
Bug: Logo is missing

### ISSUE THREAD

**Issue by lion-200** [steem-engine-exchange/steem-engine-dex#212]
**Describe the bug**
Logo image is missing for some reason. 

**To Reproduce**
- Check header for logo image

**Expected behavior**
Logo image visible

**Screenshots**
![image](https://user-images.githubusercontent.com/50720354/69962235-daedd800-150d-11ea-9c52-c18ac073a7f8.png)

**Comment by Vheissu** [comment]
Fixed.
