### ISSUE TITLE
Bug: Disable or Minimize caching on Exchange page

### ISSUE THREAD

**Issue by lion-200** [steem-engine-exchange/steem-engine-dex#214]
**Describe the bug**
On the exchange page, when a buy or sell order is placed, this is not reflected immediately on the corresponding list (buy or sell book or transaction history). This is of crucial importance for an exchange to immediately show the action result. Only after refresh the buy or sell order is visible on the buy or sell book. We need to disable caching, or minimize caching on this page. 

**To Reproduce**
1. Go to Exchange page
2. Create a buy or sell transaction
3. Check the Buy or Sell book on the left to see if your transaction is there 
4. The transaction is not there yet because of caching or not reloading of data

**Expected behavior**
Show the order or transaction immediately after placing

**Screenshots**
Order placed:
![image](https://user-images.githubusercontent.com/50720354/69962843-23f25c00-150f-11ea-9fbb-9a243a45efc8.png)

Sell order book after placing the order:
![image](https://user-images.githubusercontent.com/50720354/69962951-6a47bb00-150f-11ea-9b2f-29754d772d5f.png)

Sell order book after manually refreshing the page:
![image](https://user-images.githubusercontent.com/50720354/69962898-4dab8300-150f-11ea-8f83-e613ba010d19.png)

**Comment by Vheissu** [comment]
Caching has been disabled on the exchange screen.
