### ISSUE TITLE
Bug: Tokens table losing responsive behavior after clicking Engine Tokens

### ISSUE THREAD

**Issue by lion-200** [steem-engine-exchange/steem-engine-dex#215]
**Describe the bug**
Tokens page uses the "responsive" plugin for "DataTables". But if you click on Engine Tokens link to load the engine tokens, the table loses its responsive behavior, causing a horizontal scrollbar appearing.

**To Reproduce**
1. Go to Tokens page
2. Click on 'Engine Tokens'
3. See the horizontal scrollbar

**Expected behavior**
The expected behavior is to show the engine tokens in a responsive table. 2 ways to resolve this, 
1- we need to understand how datatable population works after data is manipulated to resolve this issue
2- create separate tables for pegged and engine tokens instead of sharing the same table

**Screenshots**
Pegged tokens:
![image](https://user-images.githubusercontent.com/50720354/69963219-040f6800-1510-11ea-8ee8-d76b27f6e79c.png)

Engine tokens:
![image](https://user-images.githubusercontent.com/50720354/69963263-20130980-1510-11ea-8084-421e2079730c.png)

**Comment by Vheissu** [comment]
This is all fixed now as tables fundamentally show data differently as well as how metrics are loaded.
