### ISSUE TITLE
Redirect to homepage or wallet on login

### ISSUE THREAD

**Issue by gadrian78** [steem-engine-exchange/steem-engine-dex#216]
I added this as a bug, because if you are logged in with one account, log out then log in with a second account, the page you were on while on the first account remains active. That can be confusing if you were looking at a certain token, which the second account doesn't have in its wallet, for example.

Plus, for me this is normal behavior. To have a "home" to start from, after you log in.

**Comment by lion-200** [comment]
Thanks for submitting this issue @gadrian78! 
Agreed. User should be redirected to homepage after login and logout. Change is applied and will be deployed to the beta environment in the upcoming release.
