### ISSUE TITLE
Suggestion: Refresh wallet page after completed transaction.

### ISSUE THREAD

**Issue by gadrian78** [steem-engine-exchange/steem-engine-dex#225]
Right now the behavior is a bit confusing, without refreshing.

I don't have capture pages to illustrate, but here are a few points that probably shouldn't go like this:
* there was a notification tooltip at the bottom of the screen announcing I successfully sent tokens, yet there was no modification on the wallet page, unless I refreshed it
* I made an exchange, both my transaction to "market" and the transaction from "market" to me were recorded in the logs, yet the wallet page showed no change, again, unless I refreshed it

**Comment by lion-200** [comment]
@Vheissu can you ping me when the caching issue on graphql is resolved so that I can check this issue again.

**Comment by Vheissu** [comment]
@lion-200 Wallet page now uses SSC calls directly side-stepping the GraphQL API. This should be good to fix now.

**Comment by lion-200** [comment]
Thanks @Vheissu ! Looks like it's fixed indeed.
@gadrian78 thanks for raising the incident. It should be fixed now!
