### ISSUE TITLE
NFT Create Screen:  field validations

### ISSUE THREAD

**Issue by bt-cryptomancer** [steem-engine-exchange/steem-engine-dex#235]
On the create screen, symbol validation should check to see if a symbol is already in use.  This should fail validation:

![image](https://user-images.githubusercontent.com/8011332/71539325-02558a80-297e-11ea-8b1a-cb95aa74d938.png)

Also, NFT Name is not allowed to be empty.
name has to be > 0 and <= 50 characters

Authorized issuing account should have the user's account name filled in by default, to make it clear that is the default if they don't change it or add more.

Also, the max number of authorized issuing accounts or authorized issuing contracts is 10.
The + control should not allow you to add more than 10 entries to each list.

**Comment by Vheissu** [comment]
@bt-cryptomancer Done. Just deployed these all to the testnet.
