### ISSUE TITLE
NFT list page: fix logic for determining if you can issue NFTs

### ISSUE THREAD

**Issue by bt-cryptomancer** [steem-engine-exchange/steem-engine-dex#236]
![image](https://user-images.githubusercontent.com/8011332/71539340-53657e80-297e-11ea-8d14-56f938e07d62.png)

In this screenshot, it shows I can issue CRITTER and MANCER (a new test token I just created).
This is incorrect.  CRITTER can only be issued by the crittermanager contract.
Whereas I can issue MANCER because my account cryptomancer is in the list of authorized issuing accounts for MANCER.
So you need to be checking that the account the user is logged in with is in the list of authorized issuing accounts.  You should not be checking the NFT definition's issuer field.

**Comment by Vheissu** [comment]
@bt-cryptomancer Done. Currently being deployed to the testnet.
