### ISSUE TITLE
NFT issue page: ensure issuance succeeds

### ISSUE THREAD

**Issue by bt-cryptomancer** [steem-engine-exchange/steem-engine-dex#237]
On the Issue NFT page, there's no feedback on whether or not an issuance was successful.  This is important because with the user currently having to type in names of data properties and select the type, it's possible that some issuance may fail (i.e. if the user types the data property name wrong or doesn't correctly remember its type).

Also, there should be a check to make sure the user has enough balance to pay the issuance fees and any tokens that get locked in the newly issued NFT instance.

**Comment by Vheissu** [comment]
Errors are now displayed using transaction validation logic. The user balances checks will be a little more involved to smoothly integrate. For now, the user will get back one or more errors if they do not have an adequate balance for locked tokens.
