### ISSUE TITLE
NFT list page: unable to edit token definition

### ISSUE THREAD

**Issue by bt-cryptomancer** [steem-engine-exchange/steem-engine-dex#250]
As the owning account for the CRITTER token, I should be able to edit token metadata such as url, description, and the token icon.  However, the edit option does not appear for me on this page:

![image](https://user-images.githubusercontent.com/8011332/72862711-81d24180-3d11-11ea-854e-ab8a963967d4.png)

Note that the ability to edit token metadata has nothing to do with the list of authorized issuing contracts & accounts.  The list of authorized issuing accounts is blank for CRITTER, so I should NOT be able to issue tokens from my cryptomancer account.  However, cryptomancer is the owner of the token itself, so that account should be able to edit metadata:

![image](https://user-images.githubusercontent.com/8011332/72862827-d8d81680-3d11-11ea-97a5-e5dbd66a3cf6.png)

Make sure for metadata editing, the web site logic is checking the issuer field of the NFT definition.  For the ability to issue tokens, the web site logic should be checking authorizedIssuingAccounts.

**Comment by Vheissu** [comment]
Fixed.

**Comment by bt-cryptomancer** [comment]
Re-opening this as the fix has introduced a new problem.  Now I can see the "issue" control.  I should not be able to issue CRITTER.

![image](https://user-images.githubusercontent.com/8011332/72886837-e3180600-3d4d-11ea-9917-1bdc69cb490d.png)

**Comment by Vheissu** [comment]
Okay, it should be good now.
