### ISSUE TITLE
Deposit / Withdraw does not list all supported tokens

### ISSUE THREAD

**Issue by bt-cryptomancer** [steem-engine-exchange/steem-engine-dex#264]
There are some tokens missing from the list of tokens in the withdraw / deposit menus.  Users have notified me that the following are missing:

TELOSSTEEM
EOSBTC
EOSSTEEM

I'm not sure if this is an exhaustive list, there may be others missing as well.  These are just the ones I know about from user feedback.

**Comment by lion-200** [comment]
Fixed & published.
