### ISSUE TITLE
Market depth chart is showing reversed price numbers on sell side

### ISSUE THREAD

**Issue by bt-cryptomancer** [steem-engine-exchange/steem-engine-dex#265]
The numbers under the depth chart on the sell side appear to be reversed, going from largest to smallest instead of smallest to largest as they should.  For example, here is the ENG market:

![image](https://user-images.githubusercontent.com/8011332/73588151-b9f33480-4508-11ea-8f8f-1d8881f154d3.png)

Notice that the first sell order is incorrectly listed as having price 6.5.  The sell side order list is also incorrectly sorted:

![image](https://user-images.githubusercontent.com/8011332/73588168-17878100-4509-11ea-8091-76294d034a0e.png)

I have to click the "more" button over and over again to actually get down to the top of the sell book.

**Comment by lion-200** [comment]
Fixed & published.
