### ISSUE TITLE
Feature: Buy ENG modal

### ISSUE THREAD

**Issue by Vheissu** [steem-engine-exchange/steem-engine-dex#91]
On the old DEX there is a modal for purchasing ENG. We need to add this into the new DEX.

![image](https://user-images.githubusercontent.com/368330/68560962-5e785400-048f-11ea-85b3-88bb18c33fe9.png)

**Comment by lion-200** [comment]
Hey @Vheissu I started implementing this popup, but I have 2 questions about this:
1- The Current Steem Balance showing in this popup in old Dex is **not** the balance available in Steem-Engine user balances, but the STEEM balance in the user's steem wallet. Is this correct behavior? With other words, shouldn't this balance be the user STEEMP balance **in** steem-engine?
2- In the old DEX's code, there is a variable defined for the steemPrice of 1 ENG token. Should we also define such a variable? Another option to default this to 1 ENG = 1 STEEM? Or do we look for the last steem price of 1 ENG from the market? This is how it looks like in the old DEX Buy ENG popup:
``<div class="ssc-cost">1 <%= Config.NATIVE_TOKEN %> = <%= SE.Params.priceSteem * 1000 %> STEEM</div>
``

**Comment by Vheissu** [comment]
@lion-200 

1. That is correct. The ENG purchase operation uses custom JSON and therefore, the user needs STEEMP in their Steem Engine account. This seems like a bug in the old DEX.

2. When you purchase ENG through the site, it's at a fixed price independent of the market itself. So it's always 1 STEEM to 1 ENG ratio as per the above. Let's hard-code, I will make this a manageable setting in the administration panel where a super admin can set the rate.

**Comment by lion-200** [comment]
Thanks man.
For 1, while testing I saw that the test amount was really deducted from my STEEM holdings. Apparently it is supposed to work this way, because it is a requestTransfer. So this is implemented just like the old DEX is, and it works.

For 2, it is hard-coded for now.
